language: csharp
solution: IronFist.sln
install:
  - nuget restore IronFist.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release IronFist.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IronTest.Tests/bin/Release/IronTest.Tests.dll