(it-should "pick up object 1 at workstation 1" (lambda ()
	(set! x 29)
	(set! y 2)
	(pick_object 1)
	(= cargo 1)))

(it-should "not pick up object 2 at workstation 1" (lambda ()
	(set! x 29)
	(set! y 2)
	(pick_object 2)
	(= cargo 0)))

(it-should "not pick up object 1 outside pick up point" (lambda ()
	(pick_object 1)
	(= cargo 0)))

(it-should "drop object 1 at workstation 2" (lambda ()
	(set! x 6)
	(set! y 1)
	(set! cargo 1)
	(drop_object)
	(= cargo 0)))

(it-should "not drop object 2 at workstation 2" (lambda ()
	(set! x 6)
	(set! y 1)
	(set! cargo 2)
	(drop_object)
	(= cargo 2)))

(it-should "not drop object outside drop off point" (lambda ()
	(set! cargo 2)
	(drop_object)
	(= cargo 2)))