(reset-robot!)
(move_forward 29)
(turn_left 1)
(move_forward 6)
(pick_object 1)
(turn_right 2)
(move_forward 6)
(turn_right 1)
(move_forward 21)
(turn_right 1)
(move_forward 7)
(turn_left 1)
(move_forward 2)
(drop_object)
(turn_left 2)
(move_forward 2)
(turn_right 1)
(move_forward 3)
(pick_object 2)
(move_forward 4)
(turn_left 1)
(move_forward 12)
(turn_right 1)
(move_forward 3)
(drop_object)
(move_forward 2)
(turn_left 1)
(move_forward 6)
(turn_left 1)
(move_forward 2)
(pick_object 3)
(turn_left 2)
(move_forward 2)
(turn_right 1)
(move_forward 5)
(turn_left 1)
(move_forward 2)
(drop_object)
(move_forward 4)
(pick_object 4)
(turn_left 2)
(move_forward 6)
(turn_right 1)
(move_forward 8)
(turn_right 1)
(move_forward 8)
(drop_object)